version: 2
jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  build: # This is our first job.
    docker: # it uses the docker executor
      - image: circleci/openjdk:8-jdk # specifically, a docker image with ruby 2.4.1
        auth:

    working_directory: ~/yorijori

    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls code down from GitHub
      - run: echo "A first hello" # This prints "A first hello" to stdout.

      - run: 
          name: Install mysql
          command: sudo apt-get install mysql-server
      - run: gradle dependencies
          # run tests and package
      - run: ./gradlew clean test

      - run:
          name: Build Docker Image
          command: ./gradlew bootRepackage -Pprod buildDocker

# Under the workflows: map, we can coordinate our two jobs, defined above.
workflows:
  version: 2
  one_and_two: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - build
